# Reduce logging level to make sure the application works with SAM local
# https://github.com/aws/serverless-java-container/issues/134
logging:
  level:
    root: INFO

spring:
  application:
    name: elink-levelup-serverless

jwt:
  secret: vG3x5+zA7tYb8qQ/Es+Rmj3UeoV6iCkYlP8ZhN2Kcqw=